//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseDemo
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040003
			public const int AddNote = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int Content = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int List = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int Save = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Title = 2130968576;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddNote = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int NoteList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int NoteListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ViewNote = 2130903043;
			
			private Layout()
			{
			}
		}
	}
}
