//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.MonoDroid
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int query = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int results = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int search_button = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int tweet_author = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int tweet_published = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int tweet_text = 2130968579;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int tweet_item = 2130903041;
			
			private Layout()
			{
			}
		}
	}
}
