//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoDroidSamples
{
	
	
	public partial class Resource
	{
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fade_out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int scale = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int shake = 2130968579;
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int flag = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000e
			public const int add_note = 2131296270;
			
			// aapt resource value: 0x7f090017
			public const int alert = 2131296279;
			
			// aapt resource value: 0x7f090020
			public const int bookmarks = 2131296288;
			
			// aapt resource value: 0x7f09000a
			public const int button = 2131296266;
			
			// aapt resource value: 0x7f09001a
			public const int chrome = 2131296282;
			
			// aapt resource value: 0x7f09000c
			public const int contact_list = 2131296268;
			
			// aapt resource value: 0x7f09000b
			public const int contact_name = 2131296267;
			
			// aapt resource value: 0x7f090019
			public const int content = 2131296281;
			
			// aapt resource value: 0x7f090011
			public const int cubeview = 2131296273;
			
			// aapt resource value: 0x7f090005
			public const int fadein_button = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int fadeout_button = 2131296260;
			
			// aapt resource value: 0x7f09001b
			public const int firefox = 2131296283;
			
			// aapt resource value: 0x7f090008
			public const int font_text = 2131296264;
			
			// aapt resource value: 0x7f09001e
			public const int ie = 2131296286;
			
			// aapt resource value: 0x7f09000f
			public const int list = 2131296271;
			
			// aapt resource value: 0x7f09000d
			public const int location_text = 2131296269;
			
			// aapt resource value: 0x7f090009
			public const int lorem = 2131296265;
			
			// aapt resource value: 0x7f090001
			public const int note_content = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int note_title = 2131296256;
			
			// aapt resource value: 0x7f09001c
			public const int opera = 2131296284;
			
			// aapt resource value: 0x7f090023
			public const int page_info = 2131296291;
			
			// aapt resource value: 0x7f090012
			public const int preference_data = 2131296274;
			
			// aapt resource value: 0x7f090018
			public const int progress = 2131296280;
			
			// aapt resource value: 0x7f09001f
			public const int refresh = 2131296287;
			
			// aapt resource value: 0x7f09001d
			public const int safari = 2131296285;
			
			// aapt resource value: 0x7f090002
			public const int save_note = 2131296258;
			
			// aapt resource value: 0x7f090006
			public const int scale_button = 2131296262;
			
			// aapt resource value: 0x7f090003
			public const int shake_button = 2131296259;
			
			// aapt resource value: 0x7f090022
			public const int share = 2131296290;
			
			// aapt resource value: 0x7f090013
			public const int start_service = 2131296275;
			
			// aapt resource value: 0x7f090014
			public const int stop_service = 2131296276;
			
			// aapt resource value: 0x7f090021
			public const int submenu = 2131296289;
			
			// aapt resource value: 0x7f090007
			public const int text = 2131296263;
			
			// aapt resource value: 0x7f090010
			public const int title = 2131296272;
			
			// aapt resource value: 0x7f090016
			public const int toast_long = 2131296278;
			
			// aapt resource value: 0x7f090015
			public const int toast_short = 2131296277;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int add_note = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int animation_demo = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int assets_demo = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int button_click = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int contacts_item = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int contacts_list = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int localization_demo = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int location_demo = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int menu_demo = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int note_list = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int note_list_item = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int opengl = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int pick_contact = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int preferences = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int receiver_demo = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int service_demo = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int text_notify = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int view_note = 2130903058;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int context_menu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int options_menu = 2131230721;
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f060000
			public const int volbeat = 2131099648;
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int localization_label = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int localization_text = 2131165184;
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int settings = 2131034112;
			
			private Xml()
			{
			}
		}
	}
}
